### ISSUE TITLE
Support for `PolicyPack` and `PolicyGroup` resources

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-pulumiservice#428] opened 2024-10-24 16:19 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be great for this provider to support both policy packs and policy groups resource management.

([context](https://pulumi.slack.com/archives/C07T20FQVNJ/p1729725343880419))

### Affected area/feature

* policy as code / crossguard
* provider

**Comment by rshade** [comment] 2024-10-25 19:30
this looks to be a duplicate of #186

**Closed** 2024-10-26 03:24 UTC
Labels: kind/enhancement, resolution/duplicate
