### ISSUE TITLE
Environment is always updated when `--refresh` is used

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-pulumiservice#385] opened 2024-08-15 03:28 UTC
### What happened?

If I run the program below, it works as expected and the Environment is correctly created ✔. However, running `pulumi up --yes --refresh` create a new revision for the Environment despite no changes in the actual code.

![Image](https://github.com/user-attachments/assets/1c4fc97e-50bf-4471-a7e9-c86571c5dd7b)
(preview 👆)

![Image](https://github.com/user-attachments/assets/b31a87a3-640e-4476-82f5-b5ad28f863aa)
(update 👆)

I think `revision` is to be expected, however `yaml` shouldn't change, right?

### Example

```python
"""A Python Pulumi program"""

import yaml
import pulumi
import pulumi_pulumiservice as pulumiservice

environment = pulumiservice.Environment("test-environment",
    name="test-environment",
    organization=pulumi.get_organization(),
    yaml = pulumi.Output.all(pulumi.Output.secret('DWedwije87dcweijdjj78e6ytgh')).apply(lambda args:
        pulumi.StringAsset(yaml.dump(
            {
                'apiKey': {
                    'fn::secret': args[0]
                }
            }
        ))
    )
)

```

### Output of `pulumi about`

```
CLI          
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  pulumiservice  0.23.1
language  python         unknown

Host     
OS       debian
Version  12.6
Arch     x86_64

This project is written in python: executable='/home/aureq/work/customers/zendesk/5662/venv/bin/python' version='3.11.9'

Current Stack: menfin/zendesk/5662

TYPE                             URN
pulumi:pulumi:Stack              urn:pulumi:5662::zendesk::pulumi:pulumi:Stack::zendesk-5662
pulumi:providers:pulumiservice   urn:pulumi:5662::zendesk::pulumi:providers:pulumiservice::default_0_23_1
pulumiservice:index:Environment  urn:pulumi:5662::zendesk::pulumiservice:index:Environment::test-environment


Found no pending operations associated with 5662

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo
Token type     personal

Dependencies:
NAME                  VERSION
pip                   24.2
pulumi-pulumiservice  0.23.1
setuptools            72.2.0
wheel                 0.44.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by IaroslavTitov** [comment] 2024-08-16 17:52
I'm quite confident this is a duplicate of https://github.com/pulumi/pulumi-pulumiservice/issues/367

I have it scheduled to work on next iteration, hopefully I can get to it, but sadly can't guarantee it with the pile of work for Pulumi UP

**Comment by komalali** [comment] 2024-08-26 19:16
Dup of https://github.com/pulumi/pulumi-pulumiservice/issues/367

**Closed by komalali** 2024-08-26 19:16 UTC
Labels: kind/bug, resolution/duplicate
